"""Tests for the parity report renderer.

The report is the artifact the project asks to be trusted on, so what is tested
here is not that it renders — it is that it cannot quietly render something
flattering. Every case below is a way the report could overstate the evidence:
a failure omitted, a divergence shown as a pass, a gap left out, a
reference-that-is-really-our-own-formula presented like an independent one.

The fixtures are small synthetic result documents rather than a real run, so
these tests neither need `parity-results.json` to exist nor care what is in it.
The check that the *committed* report matches a real run is the CI step that
regenerates it and diffs, which is a different kind of assertion and belongs
where it is.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from tests import parity, parity_report


def _claim(**overrides: Any) -> dict[str, Any]:
    claim: dict[str, Any] = {
        "entry_id": "corn.pca.scores.sklearn",
        "dataset": "corn",
        "algorithm": "pca",
        "quantity": "scores",
        "tier": str(parity.Tier.IDENTICAL),
        "passed": True,
        "software": "scikit-learn",
        "software_version": "1.9.0",
        "citation": "Generated by tests/fixtures/generate_reference_values.py",
        "rtol": 1e-8,
        "atol": 1e-10,
        "n_values": 400,
        "max_abs_diff": 1e-16,
        "max_rel_diff": 1e-14,
        "sign_aligned": True,
        "reason": "",
        "our_value": None,
        "reference_value": None,
    }
    claim.update(overrides)
    return claim


def _results(*claims: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "fixture_schema_version": 1,
        "totals": {
            "compared": len(claims),
            "passed": sum(1 for c in claims if c["passed"]),
            "failed": sum(1 for c in claims if not c["passed"]),
            **{str(tier): sum(1 for c in claims if c["tier"] == str(tier)) for tier in parity.Tier},
        },
        "not_compared": [],
        "results": list(claims),
    }


def _fixture(*entries: dict[str, Any]) -> dict[str, Any]:
    return {"schema_version": 1, "generated_at": "2026-08-22", "entries": list(entries)}


def _entry(**overrides: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "id": "corn.pca.scores.sklearn",
        "status": "sourced",
        "comparable": True,
        "notes": "",
    }
    entry.update(overrides)
    return entry


# --------------------------------------------------------------------------
# the ways it could flatter
# --------------------------------------------------------------------------


def test_a_failed_claim_is_rendered_as_a_failure_and_not_dropped() -> None:
    """A report that shows only what passed is not evidence of anything."""
    report = parity_report.render(
        _results(_claim(passed=False, max_abs_diff=0.5)), _fixture(_entry())
    )

    assert "FAILED" in report
    assert "1 claim(s) failed" in report
    assert "87 comparisons" not in report
    assert "1 comparisons, 0 passed, 1 failed" in report


def test_a_documented_divergence_shows_its_reason_and_is_not_called_a_failure() -> None:
    reason = "Theirs is a(n-1)/(n-a) F and ours is the new-sample form."
    report = parity_report.render(
        _results(
            _claim(
                entry_id="corn.pca.hotelling_t2_limit.chemotools",
                quantity="hotelling_t2_limit",
                tier=str(parity.Tier.DOCUMENTED_DIVERGENCE),
                reason=reason,
                n_values=None,
                max_abs_diff=None,
            )
        ),
        _fixture(_entry(id="corn.pca.hotelling_t2_limit.chemotools", comparable=False)),
    )

    assert reason in report
    assert "not compared — see below" in report
    assert "These are **not failures**" in report
    assert "FAILED" not in report


def test_an_unsourced_entry_is_listed_as_a_gap_with_its_reason() -> None:
    """A gap written down is a task; a gap left out is a false impression."""
    report = parity_report.render(
        _results(_claim()),
        _fixture(
            _entry(),
            _entry(
                id="corn.pls.coefficients.r_mdatools",
                status="unsourced",
                comparable=False,
                notes="R is not installed on the development machine.",
            ),
        ),
    )

    assert "## Gaps" in report
    assert "corn.pls.coefficients.r_mdatools" in report
    assert "R is not installed on the development machine." in report


def test_a_quantity_scikit_learn_does_not_report_is_marked_as_our_own_formula() -> None:
    """The agreement column looks identical either way, so the mark carries it.

    `T^2`, SPE, the cumulative explained variance curve and VIP have no
    scikit-learn counterpart; their reference values were computed here from
    scikit-learn's decomposition by our own definition. That is an independent
    decomposition and not an independent implementation, and a reader who is
    not told cannot tell.
    """
    report = parity_report.render(
        _results(_claim(quantity="hotelling_t2", sign_aligned=False)), _fixture(_entry())
    )

    assert "`hotelling_t2` †" in report
    assert "scikit-learn reports no Hotelling's T²" in report


def test_a_sign_aligned_quantity_says_so() -> None:
    report = parity_report.render(_results(_claim(quantity="loadings")), _fixture(_entry()))
    assert "`loadings` ‡" in report


def test_every_tolerance_in_use_is_printed_with_its_reason() -> None:
    """The tolerance is a claim in its own right, so it is published as one."""
    report = parity_report.render(_results(_claim(quantity="msc_corrected")), _fixture(_entry()))

    assert "**`second_implementation`**" in report
    assert parity.TOLERANCES["second_implementation"].reason in report


def test_a_scalar_claim_shows_both_numbers_and_an_array_shows_its_worst_difference() -> None:
    """`PROPOSAL.md` §10.4 promises our number beside the reference number.

    For a scalar that is the honest rendering. For an 80 x 5 score matrix it is
    not, and the worst difference over the matrix is what a reader can actually
    check.
    """
    report = parity_report.render(
        _results(
            _claim(
                entry_id="corn.pls.rmsec.sklearn",
                quantity="rmsec",
                n_values=1,
                our_value=0.04957552755533909,
                reference_value=0.049575527555338915,
                max_abs_diff=1.7e-16,
            ),
            _claim(),
        ),
        _fixture(_entry()),
    )

    assert "`0.0495755` vs `0.0495755`" in report
    assert "400 values, worst Δ 1.000e-16" in report


def test_no_cell_contains_a_pipe_that_would_break_a_table() -> None:
    """A markdown table cell holding `|` silently renders as two columns."""
    report = parity_report.render(_results(_claim()), _fixture(_entry()))

    widths: list[int] = []
    for line in report.splitlines():
        if not line.startswith("|"):
            widths.clear()
            continue
        cells = line.strip("|").split("|")
        widths.append(len(cells))
        # Every row of one table must have the header's column count. A stray
        # pipe inside a cell shows up here as a row one column too wide.
        assert widths[0] == len(cells), line


# --------------------------------------------------------------------------
# determinism, which is what makes the CI check meaningful
# --------------------------------------------------------------------------


def test_rendering_the_same_run_twice_gives_the_same_bytes() -> None:
    results, fixture = _results(_claim(), _claim(dataset="gasoline")), _fixture(_entry())
    assert parity_report.render(results, fixture) == parity_report.render(results, fixture)


def test_the_order_claims_arrived_in_does_not_change_the_report() -> None:
    """Tests may be selected, reordered or run in parallel; the report may not move."""
    first = _claim(dataset="corn", quantity="loadings")
    second = _claim(dataset="gasoline", quantity="scores")
    third = _claim(dataset="tecator", algorithm="pls", quantity="coefficients")
    fixture = _fixture(_entry())

    forwards = parity_report.render(_results(first, second, third), fixture)
    backwards = parity_report.render(_results(third, second, first), fixture)
    assert forwards == backwards


def test_a_partial_run_is_refused_rather_than_reported(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Rendering a subset would publish a coverage figure that is not true.

    `not_compared` lists comparable fixture entries that nothing checked. In a
    full run it is empty; in a `pytest -k` run it is not, and the report built
    from that would understate coverage while looking complete.
    """
    partial = tmp_path / "parity-results.json"
    partial.write_text(
        json.dumps({"not_compared": ["corn.pca.scores.sklearn"], "totals": {}, "results": []}),
        encoding="utf-8",
    )
    monkeypatch.setattr(parity, "RESULTS", partial)
    with pytest.raises(SystemExit, match="were not compared"):
        parity_report.main()
